### ISSUE TITLE
OSes on Running page regressed

### ISSUE THREAD

**Issue by andreasn** [garrett/cockpit-website-jekyll#2]
It blinks when clicked. No way to collapse an item again.

Compare: garrettlesage.com/cockpit-website-jekyll/running.html
With: http://cockpit-project.org/running.html

**Comment by garrett** [comment]
It's a different implementation that uses location hashes so the state is preserved in the URL, enhancing sharing. (People can copy and paste links for the exact instructions.)

That said, I used `pushState` (where supported, which is basically every browser now — http://caniuse.com/#feat=history) to enable toggling off instructions and to prevent jumping.

I meant to add this to the TODO, but forgot. Thanks for bringing it up!
